/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("SISTEMA DE VENTAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdpFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAlmacen = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmCompras = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmVentas = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jmEmpleados = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmAnulación = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1469056020_time-24.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1469055789_Close_Box_Red.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesión");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1469055919_sign-out.png"))); // NOI18N
        jMenuItem2.setText("Salir del Sistema");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jmAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1469056275_box.png"))); // NOI18N
        jmAlmacen.setText("Almacén");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Almacen productos.png"))); // NOI18N
        jMenuItem3.setText("Medicamentos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmAlmacen.add(jMenuItem3);

        jMenuItem15.setText("Laboratorios");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jmAlmacen.add(jMenuItem15);

        jMenuBar1.add(jmAlmacen);
        jMenuBar1.add(jMenu6);

        jmCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comprar.png"))); // NOI18N
        jmCompras.setText("Compras");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras compra.png"))); // NOI18N
        jMenuItem4.setText("Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmCompras.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras proveedor.png"))); // NOI18N
        jMenuItem5.setText("Proveedores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmCompras.add(jMenuItem5);

        jMenuBar1.add(jmCompras);

        jmVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vender.png"))); // NOI18N
        jmVentas.setText("Ventas");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventas vender.png"))); // NOI18N
        jMenuItem6.setText("Venta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jmVentas.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventas cliente.png"))); // NOI18N
        jMenuItem7.setText("Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jmVentas.add(jMenuItem7);

        jMenuBar1.add(jmVentas);

        jmEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mantenimiento.png"))); // NOI18N
        jmEmpleados.setText("Empleados");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mantenimiento empleados.png"))); // NOI18N
        jMenuItem9.setText("Farmaceúticos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jmEmpleados.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mantenimiento usuarios.png"))); // NOI18N
        jMenuItem10.setText("Bodegueros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jmEmpleados.add(jMenuItem10);

        jMenuBar1.add(jmEmpleados);

        jmAnulación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anulacion.png"))); // NOI18N
        jmAnulación.setText("Anulación");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anular venta.png"))); // NOI18N
        jMenuItem11.setText("Anular Venta");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmAnulación.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anular compra.png"))); // NOI18N
        jMenuItem12.setText("Anular Compra");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jmAnulación.add(jMenuItem12);

        jMenuBar1.add(jmAnulación);

        jmAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda.png"))); // NOI18N
        jmAyuda.setText("Ayuda");
        jmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAyudaActionPerformed(evt);
            }
        });

        jMenuItem14.setText("Manual");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jmAyuda.add(jMenuItem14);

        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jdpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static boolean ventana = false;

    public void ventanaProductos() {
        try {
            if (ventana == false) {
                Medicamentos p = new Medicamentos();
                jdpFondo.add(p);
                Dimension desktopSize = jdpFondo.getSize();
                Dimension FrameSize = p.getSize();
                p.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                p.show();
                p.setVisible(true);
                ventana = true;
            } else {
                JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
        }



    }
    static boolean ventana1 = false;

    public void ventanaCompra() {
        if (ventana1 == false) {
            Compra c = new Compra();
            jdpFondo.add(c);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = c.getSize();
            c.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            c.show();
            c.setVisible(true);
            ventana1 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana2 = false;

    public void ventanaProveedores() {
        if (ventana2 == false) {
            Proveedores pro = new Proveedores();
            jdpFondo.add(pro);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = pro.getSize();
            pro.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            pro.show();
            pro.setVisible(true);
            ventana2 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana3 = false;

    public void ventanaVenta() {
        if (ventana3 == false) {
            Venta v = new Venta();
            jdpFondo.add(v);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = v.getSize();
            v.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            v.show();
            v.setVisible(true);
            ventana3 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana4 = false;

    public void ventanaEmpleados() {
        if (ventana4 == false) {
            Farmaceuticos e = new Farmaceuticos();
            jdpFondo.add(e);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = e.getSize();
            e.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            e.show();
            e.setVisible(true);
            ventana4 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana5 = false;

    public void ventanaUsuarios() {
        if (ventana5 == false) {
            Usuarios u = new Usuarios();
            jdpFondo.add(u);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = u.getSize();
            u.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            u.show();
            u.setVisible(true);
            ventana5 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana6 = false;

    public void ventanaAnular_Venta() {
        if (ventana6 == false) {
            Anular_Venta av = new Anular_Venta();
            jdpFondo.add(av);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = av.getSize();
            av.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            av.show();
            av.setVisible(true);
            ventana6 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana7 = false;

    public void ventanaAnular_Compra() {
        if (ventana7 == false) {
            Anular_Compra ac = new Anular_Compra();
            jdpFondo.add(ac);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = ac.getSize();
            ac.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            ac.show();
            ac.setVisible(true);
            ventana7 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana8 = false;

    public void ventanaManual() {
        if (ventana8 == false) {
            Manual a = new Manual();
            jdpFondo.add(a);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = a.getSize();
            a.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            a.show();
            a.setVisible(true);
            ventana8 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    static boolean ventana9 = false;

    public void ventanaClientes() {
        if (ventana9 == false) {
            Clientes c = new Clientes();
            jdpFondo.add(c);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = c.getSize();
            c.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            c.show();
            c.setVisible(true);
            ventana9 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
  static boolean ventana10 = false;

    public void ventanaLaboratorios() {
        if (ventana10 == false) {
            Laboratorios l = new Laboratorios();
            jdpFondo.add(l);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = l.getSize();
            l.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            l.show();
            l.setVisible(true);
            ventana10 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    
     static boolean ventana11 = false;

    public void ventanaBodegueros() {
        if (ventana11 == false) {
            Bodeguero l = new Bodeguero();
            jdpFondo.add(l);
            Dimension desktopSize = jdpFondo.getSize();
            Dimension FrameSize = l.getSize();
            l.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            l.show();
            l.setVisible(true);
            ventana11 = true;
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta...!", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }

    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ventanaProductos();



    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ventanaCompra();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ventanaProveedores();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ventanaVenta();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ventanaClientes();        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ventanaEmpleados();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
       ventanaBodegueros();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        ventanaAnular_Venta();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        ventanaAnular_Compra();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAyudaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmAyudaActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        ventanaManual();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
         ventanaLaboratorios();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JDesktopPane jdpFondo;
    public static javax.swing.JMenu jmAlmacen;
    public static javax.swing.JMenu jmAnulación;
    public static javax.swing.JMenu jmAyuda;
    public static javax.swing.JMenu jmCompras;
    public static javax.swing.JMenu jmEmpleados;
    public static javax.swing.JMenu jmVentas;
    // End of variables declaration//GEN-END:variables
}
